// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqxglbmvluaxbgyrzztc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxeGdsYm12bHVheGJneXJ6enRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDkxNzUsImV4cCI6MjA2NTQ4NTE3NX0.4ebeLuHpNExLs_YPFVnj-1ec0y12h0i1KtOony1zG6w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);